var annotated_dup =
[
    [ "action", "structaction.html", null ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "DirectionalLight", "class_directional_light.html", "class_directional_light" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "ForwardRenderer3DLayer", "class_forward_renderer3_d_layer.html", null ],
    [ "geRef", "classge_ref.html", null ],
    [ "geRendRef", "classge_rend_ref.html", null ],
    [ "Input", "class_input.html", null ],
    [ "Lights", "class_lights.html", "class_lights" ],
    [ "Material", "class_material.html", "class_material" ],
    [ "MaterialSorter", "struct_material_sorter.html", null ],
    [ "Mesh", "class_mesh.html", "class_mesh" ],
    [ "Meshes", "class_meshes.html", "class_meshes" ],
    [ "MeshThing", "class_mesh_thing.html", "class_mesh_thing" ],
    [ "Model", "class_model.html", "class_model" ],
    [ "ModelSlaveThing", "class_model_slave_thing.html", "class_model_slave_thing" ],
    [ "ModelThing", "class_model_thing.html", "class_model_thing" ],
    [ "PointLight", "class_point_light.html", "class_point_light" ],
    [ "Position", "class_position.html", "class_position" ],
    [ "RenderLayer", "class_render_layer.html", null ],
    [ "Rotation", "class_rotation.html", "class_rotation" ],
    [ "Scale", "class_scale.html", "class_scale" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "ShaderProgram", "class_shader_program.html", "class_shader_program" ],
    [ "Shaders", "class_shaders.html", "class_shaders" ],
    [ "SpatialThing", "class_spatial_thing.html", "class_spatial_thing" ],
    [ "Texture", "class_texture.html", "class_texture" ],
    [ "Thing", "class_thing.html", "class_thing" ],
    [ "Transform", "class_transform.html", "class_transform" ],
    [ "Vector3", "class_vector3.html", "class_vector3" ],
    [ "Window", "class_window.html", "class_window" ]
];